config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'welcome#home'
    get 'welcome/connect', to: 'welcome#connect'
    get 'projects/index', to: 'projects#index'
    get 'projects/js', to: 'projects#js'
    get 'projects/rails', to: 'projects#rails'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  end

  def rails
  end

  def js
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

  def connect
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div id="header" class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= link_to "mark modak", root_path, id: "logo" %></h1>

    <p class="lead"> <%= link_to "software engineer", projects_index_path, id: "logo" %>
      | <%= link_to "learner", welcome_connect_path, id: "logo" %> |
       <a href="https://www.kentdenver.org/about/directory?utf8=%E2%9C%93&const_search_group_ids=&const_search_role_ids=1&const_search_keyword=&const_search_first_name=Mark&const_search_last_name=Modak" id="logo">teacher</a>
       | <a href="https://www.instagram.com/markmodak/" id="logo">sweater</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>markmodak</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id='home-body'>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
<div class="button_wrapper">
  <div class="well well-lg this_box">
    <%= link_to "Rails/Ruby Projects", projects_rails_path, id: "word" %>
  </div>
  <div class="well well-lg this_box">
    <%= link_to "JS/HTML/CSS Projects", projects_js_path, id: "word" %>
  </div>

</div>

app/views/projects/js.html.erb
<div class="button_wrapper">
  <div class="well well-lg each_box">
    <a href="https://grade-converter-earthtreks.herokuapp.com/" id="word">Grade Converter</a>
    <p><i>Production</i></p>
    <p></p>
    <p id="smaller">An interactive site built in JavaScript with HTML/CSS styling. This app
    is in production and was built to help local climbers compare grades for routes at
    area gyms and local crags. <a href="https://www.sierra.com/blog/climbing/rock-climbing-grades-explained/" id="word"><u>For more information on climbing grades.</u></a> This site is hosted on Heroku, which
    does not naturally host JS/HTML/CSS sites. For more information on how I hosted the site there with the PHP buildpack, please read my <a href="https://medium.com/@markevan100/variety-making-things-you-can-see-while-studying-backend-development-16dd705bf31c" id="word"><u>blog.</u></a></p>
  </div>
  <div class="well well-lg each_box">
    <a href="https://github.com/markevan100/react-burger-builder" id="word">Burger Orders</a>
    <p><i>Development</i></p>
    <p></p>
    <p id="smaller">A React SPA with a Firebase backend. This app connects to
      the REST API through Axios Http calls and routes pages with React Router. </p>
  </div>
  <div class="well well-lg each_box">
    <a href="https://github.com/markevan100/tictactoe_react" id="word">React: tic-tac-toe</a>
    <p><i>Development</i></p>
    <p></p>
    <p id="smaller">My first React site, using a react tutorial. </p>
  </div>
  <div class="well well-lg each_box">
    <a href="https://github.com/markevan100/react-todo-traversy" id="word">React: ToDo</a>
    <p><i>Development</i></p>
    <p></p>
    <p id="smaller">My second React site, using a different tutorial. </p>
  </div>
</div>

app/views/projects/rails.html.erb
<div class="button_wrapper">
  <div class="well well-lg each_box">
    <a href="https://github.com/markevan100/route_finder" id="word">Route Finder</a>
    <p><i>Development</i></p>
    <p></p>
    <p id="smaller">A Rails site that accesses three 3rd party API's using the HTTParty Gem, performs webscraping with the Nokogiri Gem,
    authenticates users with the Devise Gem, and implements a relational database through a Rails many-to-many relationship. This site allows users
    to search, view, and save different climbing routes. To read my
    blog about how I set up webscraping, <a href="https://medium.com/@markevan100/basic-web-scraping-in-rails-using-nokogiri-7e8a2504cbc6" id="word"><u>click here</u></a>.
     If you would like to learn more about how I set up my API calls, <a href="https://medium.com/@markevan100/api-calls-in-rails-from-basic-to-better-and-some-important-considerations-3bf04285c8a2" id="word"><u>click here</u></a>. </u></a></p>
  </div>
  <div class="well well-lg each_box">
    <a href="https://climb-kent.herokuapp.com/" id="word">Climbing Team</a>
    <p><i>Production</i></p>
    <p></p>
    <p id="smaller">A site designed for the coaches of the Kent Denver Rock Climbing Team. This site was
    built on Rails. It integrats three different databases and allows coaches to
  update and record daily practices, track the roster, and add important contacts.</p>
  </div>
  <div class="well well-lg each_box">
    <a href="https://polar-island-64116.herokuapp.com/" id="word">The Message Butler</a>
    <p><i>Development</i></p>
    <p></p>
    <p id="smaller">Chatroom site built on Rails. This site integrates WebSockets with ActionCable to
    enable realtime updates. For projection, the site uses Redis. Read my <a href="https://medium.com/@markevan100/setting-up-redis-on-a-rails-app-for-deployment-through-heroku-1b278d58f8ed" id="word"><u>blog</u></a> for more information about
    how I integrated Redis. </p>
  </div>
  <div class="well well-lg each_box">
    <a href="https://github.com/markevan100/digest" id="word">The Digest Digest</a>
    <p><i>Development</i></p>
    <p></p>
    <p id="smaller">My largest project to date, this development stage app was independently commisioned.
    Currently, the app features multiple databases, CRUD capabilities, and styled post and index pages. </p>
  </div>
  <div class="well well-lg each_box">
    <a href="https://wallstreet-bully.herokuapp.com" id="word">Wallstreet Bully</a>
    <p><i>Production</i></p>
    <p></p>
    <p id="smaller">A stock tracker app on Rails that uses Devise for user/session management and Ajax
    for quick updating of pages without full page reload. This app also employs search capability both through
    an external gem and internally with users. </p>
  </div>


</div>

app/views/welcome/connect.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="well well-lg one_box">
        Let's Connect!
        <p></p>
        <p id="smallish">I'm making a career switch from teaching high school Spanish to the tech industry.
           I am thrilled to have the chance to experience the intersection of spoken languages
            and computer programming languages. Currently, I write Ruby and JS, but am learning more and
            expanding my knowledge base every day. I thrive on collaboraiton, pair programming, and just
          chatting about the world of development. Please don't hesitate to reach out!</p>
          <p></p>
          <p></p>
          <p><span class="glyphicon glyphicon-envelope"></span> markevan100@gmail.com</p>
          <p><span class="glyphicon glyphicon-cloud"></span> <a href="https://github.com/markevan100" id="word">github.com/markevan100</a></p>
          <p><span class="glyphicon glyphicon-phone"></span> (240) 498 - 6179</p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<div class="button_wrapper">
  <div class="well well-lg each_box">
    <%= link_to "See My Projects", projects_index_path, id: "word" %>
  </div>
  <div class="well well-lg each_box">
    <a href="https://medium.com/@markevan100" id="word">Read a Blog</a>
  </div>
  <div class="well well-lg each_box">
    <%= link_to "Connect", welcome_connect_path, id: "word" %>
  </div>

</div>